version: "2.2"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    container_name: flinkzookeeper
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka
    container_name: kafka
    deploy:
      resources:
        limits:
          memory: 2048M
    depends_on:
      - zookeeper
    ports:
      - 9091:9091
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BOOTSTRAP.SERVERS: 'kafka:29092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092,INSIDE://:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  jobmanager-1:
    image: flink:1.13.0-scala_2.11
    hostname: jobmanager-1
    container_name: jobmanager-1
    depends_on:
      - zookeeper
    ports:
      - 8081:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        high-availability: zookeeper
        high-availability.cluster-id: gaas
        high-availability.storageDir: file:///shared/ha
        high-availability.zookeeper.path.root: /flink/gaas
        high-availability.zookeeper.quorum: zookeeper:2181
        state.checkpoints.dir: file:///shared/checkpoints/external
    volumes:
      - ./shared/flink:/shared

  jobmanager-2:
    image: flink:1.13.0-scala_2.11
    hostname: jobmanager-2
    container_name: jobmanager-2
    depends_on:
      - zookeeper
    ports:
      - 8082:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        high-availability: zookeeper
        high-availability.cluster-id: gaas
        high-availability.storageDir: file:///shared/ha
        high-availability.zookeeper.path.root: /flink/gaas
        high-availability.zookeeper.quorum: zookeeper:2181
        state.checkpoints.dir: file:///shared/checkpoints/external
    volumes:
      - ./shared/flink:/shared

  taskmanager-1:
    image: flink:1.13.0-scala_2.11
    hostname: taskmanager-1
    container_name: taskmanager-1
    depends_on:
      - zookeeper
      - jobmanager-1
      - jobmanager-2
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        taskmanager.numberOfTaskSlots: 2
        high-availability: zookeeper
        high-availability.cluster-id: gaas
        high-availability.storageDir: file:///shared/ha
        high-availability.zookeeper.path.root: /flink/gaas
        high-availability.zookeeper.quorum: zookeeper:2181
        state.checkpoints.dir: file:///shared/checkpoints/external
        restart-strategy: fixeddelay
        restart-strategy.fixed-delay.attempts: 3
    volumes:
      - ./shared/flink:/shared

  taskmanager-2:
    image: flink:1.13.0-scala_2.11
    hostname: taskmanager-2
    container_name: taskmanager-2
    depends_on:
      - zookeeper
      - jobmanager-1
      - jobmanager-2
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        taskmanager.numberOfTaskSlots: 2
        high-availability: zookeeper
        high-availability.cluster-id: gaas
        high-availability.storageDir: file:///shared/ha
        high-availability.zookeeper.path.root: /flink/gaas
        high-availability.zookeeper.quorum: zookeeper:2181
        state.checkpoints.dir: file:///shared/checkpoints/external
        restart-strategy: fixeddelay
        restart-strategy.fixed-delay.attempts: 3
    volumes:
      - ./shared/flink:/shared