version: '2'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - ./:/var/lib/cassandra/
